/* ============================================================
   LISTADO DE FOTOS — ARCHIVO AUTOMATICO, NO EDITAR A MANO
   Lo genera actualizar-fotos.py leyendo las carpetas de
   images/trabajos/
   Si agregas o sacas fotos, volve a correr ACTUALIZAR.bat
   ============================================================ */
const FOTOS = {
  "awara": [
    "images/trabajos/awara/awara.jpg",
    "images/trabajos/awara/awara-1.jpg",
    "images/trabajos/awara/awara-1-1.jpg",
    "images/trabajos/awara/awara-2.jpg",
    "images/trabajos/awara/awara-2-1.jpg",
    "images/trabajos/awara/awara-3.jpg",
    "images/trabajos/awara/awara-3-1.jpg",
    "images/trabajos/awara/awara-4.jpg",
    "images/trabajos/awara/awara-4-1.jpg",
    "images/trabajos/awara/awara-5.jpg",
    "images/trabajos/awara/awara-5-1.jpg",
    "images/trabajos/awara/awara-6.jpg"
  ],
  "backup": [
    "images/trabajos/backup/backup.jpg",
    "images/trabajos/backup/backup-1.jpg",
    "images/trabajos/backup/backup-1-1.jpg",
    "images/trabajos/backup/backup-2.jpg"
  ],
  "chiller": [
    "images/trabajos/chiller/chiller.jpg",
    "images/trabajos/chiller/chiller-1.jpg",
    "images/trabajos/chiller/chiller-1-1.jpg",
    "images/trabajos/chiller/chiller-2.jpg",
    "images/trabajos/chiller/chiller-2-1.jpg",
    "images/trabajos/chiller/chiller-3.jpg",
    "images/trabajos/chiller/chiller-3-1.jpg",
    "images/trabajos/chiller/chiller-4.jpg",
    "images/trabajos/chiller/chiller-4-1.jpg",
    "images/trabajos/chiller/chiller-5.jpg",
    "images/trabajos/chiller/chiller-5-1.jpg",
    "images/trabajos/chiller/chiller-6.jpg",
    "images/trabajos/chiller/chiller-6-1.jpg",
    "images/trabajos/chiller/chiller-7.jpg",
    "images/trabajos/chiller/chiller-7-1.jpg",
    "images/trabajos/chiller/chiller-8.jpg",
    "images/trabajos/chiller/chiller-8-1.jpg",
    "images/trabajos/chiller/chiller-9.jpg",
    "images/trabajos/chiller/chiller-9-1.jpg",
    "images/trabajos/chiller/chiller-10.jpg",
    "images/trabajos/chiller/chiller-10-1.jpg",
    "images/trabajos/chiller/chiller-11.jpg"
  ],
  "fleming-solar": [
    "images/trabajos/fleming-solar/20261003-183910.jpg",
    "images/trabajos/fleming-solar/20261003-183930.jpg",
    "images/trabajos/fleming-solar/20261003-184005.jpg",
    "images/trabajos/fleming-solar/20261003-184025.jpg",
    "images/trabajos/fleming-solar/20261003-202843.jpg",
    "images/trabajos/fleming-solar/20261003-210222.jpg"
  ],
  "maimara": [
    "images/trabajos/maimara/maimara.jpg",
    "images/trabajos/maimara/maimara-1.jpg",
    "images/trabajos/maimara/maimara-1-1.jpg",
    "images/trabajos/maimara/maimara-2.jpg",
    "images/trabajos/maimara/maimara-2-1.jpg",
    "images/trabajos/maimara/maimara-3.jpg"
  ],
  "metalnoa": [
    "images/trabajos/metalnoa/metalnoa.jpg",
    "images/trabajos/metalnoa/metalnoa-1.jpg",
    "images/trabajos/metalnoa/metalnoa-1-1.jpg",
    "images/trabajos/metalnoa/metalnoa-2.jpg",
    "images/trabajos/metalnoa/metalnoa-2-1.jpg",
    "images/trabajos/metalnoa/metalnoa-3.jpg",
    "images/trabajos/metalnoa/metalnoa-3-1.jpg",
    "images/trabajos/metalnoa/metalnoa-4.jpg",
    "images/trabajos/metalnoa/metalnoa-4-1.jpg",
    "images/trabajos/metalnoa/metalnoa-5.jpg"
  ],
  "parque-fotovoltaico": [
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-1-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-2.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-2-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-3.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-3-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-4.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-4-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-5.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-5-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-6.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-6-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-7.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-7-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-8.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-8-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-9.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-9-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-10.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-10-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-11.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-11-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-12.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-12-1.jpg",
    "images/trabajos/parque-fotovoltaico/parque-fotovoltaico-13.jpg"
  ],
  "porotera": [
    "images/trabajos/porotera/porotera.jpg",
    "images/trabajos/porotera/porotera-1.jpg",
    "images/trabajos/porotera/porotera-1-1.jpg",
    "images/trabajos/porotera/porotera-2.jpg",
    "images/trabajos/porotera/porotera-2-1.jpg",
    "images/trabajos/porotera/porotera-3.jpg",
    "images/trabajos/porotera/porotera-3-1.jpg",
    "images/trabajos/porotera/porotera-4.jpg",
    "images/trabajos/porotera/porotera-4-1.jpg",
    "images/trabajos/porotera/porotera-5.jpg",
    "images/trabajos/porotera/porotera-5-1.jpg",
    "images/trabajos/porotera/porotera-6.jpg",
    "images/trabajos/porotera/porotera-6-1.jpg",
    "images/trabajos/porotera/porotera-7.jpg",
    "images/trabajos/porotera/porotera-7-1.jpg",
    "images/trabajos/porotera/porotera-8.jpg"
  ],
  "posco": [
    "images/trabajos/posco/posco.jpg",
    "images/trabajos/posco/posco-1.jpg",
    "images/trabajos/posco/posco-2.jpg",
    "images/trabajos/posco/posco-3.jpg",
    "images/trabajos/posco/posco-4.jpg"
  ],
  "posco-pat2026": [
    "images/trabajos/posco-pat2026/20260922-174958.jpg",
    "images/trabajos/posco-pat2026/20260922-180247.jpg",
    "images/trabajos/posco-pat2026/20260922-180756.jpg",
    "images/trabajos/posco-pat2026/20260922-180926.jpg",
    "images/trabajos/posco-pat2026/20260923-092849.jpg",
    "images/trabajos/posco-pat2026/20260923-094944.jpg",
    "images/trabajos/posco-pat2026/20260923-095552.jpg",
    "images/trabajos/posco-pat2026/20260923-095901.jpg",
    "images/trabajos/posco-pat2026/20260923-095907.jpg",
    "images/trabajos/posco-pat2026/20260923-100741.jpg",
    "images/trabajos/posco-pat2026/20260923-101738.jpg"
  ],
  "seccionadora": [
    "images/trabajos/seccionadora/seccionadora.jpg",
    "images/trabajos/seccionadora/seccionadora-1.jpg",
    "images/trabajos/seccionadora/seccionadora-1-1.jpg",
    "images/trabajos/seccionadora/seccionadora-2.jpg",
    "images/trabajos/seccionadora/seccionadora-2-1.jpg",
    "images/trabajos/seccionadora/seccionadora-3.jpg"
  ],
  "tambo": [
    "images/trabajos/tambo/tambo.jpg",
    "images/trabajos/tambo/tambo-1.jpg",
    "images/trabajos/tambo/tambo-1-1.jpg",
    "images/trabajos/tambo/tambo-2.jpg"
  ],
  "vissionary-solar": [
    "images/trabajos/vissionary-solar/20260831-181435.jpg",
    "images/trabajos/vissionary-solar/20260901-194328.jpg",
    "images/trabajos/vissionary-solar/20260902-182024.jpg",
    "images/trabajos/vissionary-solar/20260903-145506.jpg",
    "images/trabajos/vissionary-solar/20260903-183827.jpg",
    "images/trabajos/vissionary-solar/20260904-200520.jpg",
    "images/trabajos/vissionary-solar/20260904-200532.jpg",
    "images/trabajos/vissionary-solar/20260904-221843.jpg",
    "images/trabajos/vissionary-solar/20260905-142438.jpg",
    "images/trabajos/vissionary-solar/20260905-203154.jpg",
    "images/trabajos/vissionary-solar/20260906-115958.jpg",
    "images/trabajos/vissionary-solar/20260906-115959.jpg",
    "images/trabajos/vissionary-solar/20260906-121318-1.jpg",
    "images/trabajos/vissionary-solar/20260906-121332.jpg",
    "images/trabajos/vissionary-solar/20260911-225346.jpg",
    "images/trabajos/vissionary-solar/20260911-225348.jpg",
    "images/trabajos/vissionary-solar/20261002-181243.jpg",
    "images/trabajos/vissionary-solar/20261002-181518.jpg"
  ]
};
